services:
  - type: web
    name: aroga-production
    env: docker
    plan: free
    repo: https://github.com/QInvst/Aroga-Production.git
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AZURE_SQL_CONN
        sync: false
      - key: AZURE_CONNECTION_STRING
        sync: false
      - key: AZURE_CONTAINER_NAME
        sync: false
